@startuml
title PythonMusic

package "pythonmusic" {
  package "music" {
    class Note {
      +pitch: int
      +dynamic: int
      +duration: float
      --Inits--
      +Note(pitch: int, duration: float)
      +Note(pitch: int, duration: float, dynamic: int)
      --Rest--
      +is_rest() -> bool
      +as_rest() -> Note
      --Statics--
      {static}+rest(duration: float) -> Note
    }

    class ChordAttribute {}

    class Chord {
      +notes: [Note]
      +attributes: [ChordAttribute]
      --Inits--
      +Chord()
      +Chord(notes: [Note])
      --Calculated Properties--
      +count() -> int
      +length() -> float
      --Mutation--
      +add_note(note: Note)
      +add_notes(notes: [Note])
      +remove_note(index: int) -> Note
      --Queries--
      +min_pitch() -> int?
      +max_pitch() -> int?
      +min_dynamic() -> int?
      +max_dynamic() -> int?
      +min_duration() -> float?
      +max_duration() -> float?

    }

    class Phrase {
      +notes: [Note | Chord]
      --Inits--
      +Phrase()
      +Phrase(notes: [Note | Chord])
      +Phrase(pitches: [int] | int, durations: [float] | float, dynamics: [int] | int)
      --Calculated Properties--
      +count() -> int
      +length() -> float
      --Mutation--
      +add_note(note: Note)
      +add_chord(chord: Chord)
      +add_notes(notes: [Notes | Chord])
      +add_notes(pitches: [int] | int, durations: [float] | float, dynamics: [int] | int))
      +remove_note(index: int) -> (Note | Chord)?
      +clear()
      --Queries--
      +min_pitch() -> int?
      +max_pitch() -> int?
      +min_dynamic() -> int?
      +max_dynamic() -> int?
      +min_duration() -> float?
      +max_duration() -> float?
    }

    class Part {
      +title: str?
      +phrases: [Phrase]
      +instrument: int
      +channel: int
      +panning: int
      --Inits--
      +Part()
      +Part(title: str?, instrument: int, channel: int, phrases: [Phrase], panning: int)
      --Calculated Properties--
      +count() -> int
      +length() -> float
      --Mutation--
      +add_phrase(phrase: Phrase, start_time: float?)
      +add_phrases(phrases: [Phrase], start_time: ([float] | float)?)
      +remove_phrase(index: int) -> Phrase?
      +clear()
    }

    class Score {
      +title: str?
      +parts: [Part]
      +tempo: float
      --Inits--
      +Score(title: str?)
      +Score(title: str?, tempo: float, parts: [Part])
      --Calculated Properties--
      +count() -> int
      +length() -> float
      --Mutation--
      +add_part(part: Part)
      +add_parts(parts: [Part])
      +remove_part(index: int) -> Part
      +clear()
    }
  }

  music.Chord -> music.ChordAttribute
  music.Chord -l-> music.Note
  music.Phrase -d-> music.Note
  music.Phrase -d-> music.Chord
  music.Part -d-> music.Phrase
  music.Score -l-> music.Part

  package osc {
    class OscClient {
      -depends on library API
      --Inits--
      +OscClient(ip: str, prt: int)
      --Messages--
      +send_message(path: str, data: any?)
      +is_open() -> bool
      --Cleanup--
      +close()
    }

    class OscHost {
      +depends on library API
      --Inits--
      +OscHost(port: int)
      --Callbacks--
      +on_message(callback: fn(path: str, data: any?))
      --Cleanup--
      +close()
    }
  }

  package io {
    class MidiFile {
      -depends on library API
      --Inits--
      +MidiFile(score: Score)
      +MidiFile(path: str | Path)
      --Get--
      +score() -> Score
      --Write--
      +export(path: str | Path)
      --Cleanup--
      +close
    }

    class MidiReceiver {
      -prints_messages: bool
      -depends on library API
      --Inits--
      +MidiReceiver(device: str | int)
      --Generic Callbacks--
      +on_message(callback: fn(message: str, channel: int, data: (any?, any?)))
      --Specific Callback--
      +on_note_off(callback: fn(pitch: int, ...))
      +on_note_on(callback: fn(pitch: int, ...))
      etc.
      --Debug--
      +prints_messages() -> bool
      +print_messages(state: bool, target: any?)
      --Cleanup--
      +close()
    }

    class MidiSender {
      -depends on library API
      --Inits--
      MidiSender(device: str | int)
      --Play--
      +play(note: Note | Chord, instrument: int, channel: int, panning: int, tempo: float)
      +play(notes: [Note | Chord], instrument: int, channel: int, panning: int, tempo: float)
      +play(phrase: Phrase, instrument: int, channel: int, panning: int, tempo: float)
      +play(part: Part, tempo: float)
      +play(score: Score)
      --Generic Messages--
      +send_message(type: str, channel: int, data: (any?, any?))
      --Specific Messages--
      +send_note_on(note: Note, channel: int, instrument: int, panning: int)
      +send_note_off(note: Note, channel: int)
      +send_note_off(pitch: int, channel: int)
      +send_all_notes_off()
      etc.
      --Cleanup--
      +close()
    }

    circle "get_midi_devices() -> [str]"
    circle "select_midi_device_prompt() -> str?"
  }

  abstract class playback {
    +play_midi(note: Note | Chord, instrument: int, channel: int, panning: int, tempo: float)
    +play_midi(notes: [Note | Chord], instrument: int, channel: int, panning: int, tempo: float)
    +play_midi(phrase: Phrase, instrument: int, channel: int, panning: int, tempo: float)
    +play_midi(part: Part, tempo: float)
    +play_midi(score: Score)
  }

  package constants {
    package "pitches" {}
    package "dynamics" {}
    package "durations" {}
    package "panning" {}
    package "instruments" {}
    package "scales" {}
    package "modes" {}
    package "percussion" {}
  }

  /'layout'/
  music -[hidden]l-> io
  io --[hidden]d-> constants
  io --[hidden]d-> osc
}

package "python-osc" {}
package "mido" {}
package "pygame" {}

pythonmusic.osc -d-> "python-osc"
pythonmusic.io -u-> "mido"
mido -> pygame : virtual synth

@enduml
